export type CountryOption = {
  code: string;
  name: string;
  flagUrl: string;
};

const toFlagEmoji = (countryCode: string): string =>
  countryCode
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));

export const countryOptions: CountryOption[] = [
  { code: "US", name: "United States", flagUrl: "https://flagcdn.com/w40/us.png" },
  { code: "GB", name: "United Kingdom", flagUrl: "https://flagcdn.com/w40/gb.png" },
  { code: "CA", name: "Canada", flagUrl: "https://flagcdn.com/w40/ca.png" },
  { code: "AU", name: "Australia", flagUrl: "https://flagcdn.com/w40/au.png" },
  { code: "DE", name: "Germany", flagUrl: "https://flagcdn.com/w40/de.png" },
  { code: "FR", name: "France", flagUrl: "https://flagcdn.com/w40/fr.png" },
  { code: "IT", name: "Italy", flagUrl: "https://flagcdn.com/w40/it.png" },
  { code: "ES", name: "Spain", flagUrl: "https://flagcdn.com/w40/es.png" },
  { code: "NL", name: "Netherlands", flagUrl: "https://flagcdn.com/w40/nl.png" },
  { code: "BE", name: "Belgium", flagUrl: "https://flagcdn.com/w40/be.png" },
  { code: "SE", name: "Sweden", flagUrl: "https://flagcdn.com/w40/se.png" },
  { code: "NO", name: "Norway", flagUrl: "https://flagcdn.com/w40/no.png" },
  { code: "DK", name: "Denmark", flagUrl: "https://flagcdn.com/w40/dk.png" },
  { code: "FI", name: "Finland", flagUrl: "https://flagcdn.com/w40/fi.png" },
  { code: "PL", name: "Poland", flagUrl: "https://flagcdn.com/w40/pl.png" },
  { code: "AT", name: "Austria", flagUrl: "https://flagcdn.com/w40/at.png" },
  { code: "CH", name: "Switzerland", flagUrl: "https://flagcdn.com/w40/ch.png" },
  { code: "IE", name: "Ireland", flagUrl: "https://flagcdn.com/w40/ie.png" },
  { code: "PT", name: "Portugal", flagUrl: "https://flagcdn.com/w40/pt.png" },
  { code: "GR", name: "Greece", flagUrl: "https://flagcdn.com/w40/gr.png" },
  { code: "CZ", name: "Czech Republic", flagUrl: "https://flagcdn.com/w40/cz.png" },
  { code: "RO", name: "Romania", flagUrl: "https://flagcdn.com/w40/ro.png" },
  { code: "HU", name: "Hungary", flagUrl: "https://flagcdn.com/w40/hu.png" },
  { code: "UA", name: "Ukraine", flagUrl: "https://flagcdn.com/w40/ua.png" },
  { code: "TR", name: "Turkey", flagUrl: "https://flagcdn.com/w40/tr.png" },
  { code: "RU", name: "Russia", flagUrl: "https://flagcdn.com/w40/ru.png" },
  { code: "IN", name: "India", flagUrl: "https://flagcdn.com/w40/in.png" },
  { code: "CN", name: "China", flagUrl: "https://flagcdn.com/w40/cn.png" },
  { code: "JP", name: "Japan", flagUrl: "https://flagcdn.com/w40/jp.png" },
  { code: "KR", name: "South Korea", flagUrl: "https://flagcdn.com/w40/kr.png" },
  { code: "SG", name: "Singapore", flagUrl: "https://flagcdn.com/w40/sg.png" },
  { code: "MY", name: "Malaysia", flagUrl: "https://flagcdn.com/w40/my.png" },
  { code: "TH", name: "Thailand", flagUrl: "https://flagcdn.com/w40/th.png" },
  { code: "ID", name: "Indonesia", flagUrl: "https://flagcdn.com/w40/id.png" },
  { code: "PH", name: "Philippines", flagUrl: "https://flagcdn.com/w40/ph.png" },
  { code: "VN", name: "Vietnam", flagUrl: "https://flagcdn.com/w40/vn.png" },
  { code: "PK", name: "Pakistan", flagUrl: "https://flagcdn.com/w40/pk.png" },
  { code: "BD", name: "Bangladesh", flagUrl: "https://flagcdn.com/w40/bd.png" },
  { code: "LK", name: "Sri Lanka", flagUrl: "https://flagcdn.com/w40/lk.png" },
  { code: "AE", name: "United Arab Emirates", flagUrl: "https://flagcdn.com/w40/ae.png" },
  { code: "SA", name: "Saudi Arabia", flagUrl: "https://flagcdn.com/w40/sa.png" },
  { code: "QA", name: "Qatar", flagUrl: "https://flagcdn.com/w40/qa.png" },
  { code: "KW", name: "Kuwait", flagUrl: "https://flagcdn.com/w40/kw.png" },
  { code: "BH", name: "Bahrain", flagUrl: "https://flagcdn.com/w40/bh.png" },
  { code: "OM", name: "Oman", flagUrl: "https://flagcdn.com/w40/om.png" },
  { code: "IL", name: "Israel", flagUrl: "https://flagcdn.com/w40/il.png" },
  { code: "JO", name: "Jordan", flagUrl: "https://flagcdn.com/w40/jo.png" },
  { code: "LB", name: "Lebanon", flagUrl: "https://flagcdn.com/w40/lb.png" },
  { code: "EG", name: "Egypt", flagUrl: "https://flagcdn.com/w40/eg.png" },
  { code: "ZA", name: "South Africa", flagUrl: "https://flagcdn.com/w40/za.png" },
  { code: "NG", name: "Nigeria", flagUrl: "https://flagcdn.com/w40/ng.png" },
  { code: "KE", name: "Kenya", flagUrl: "https://flagcdn.com/w40/ke.png" },
  { code: "GH", name: "Ghana", flagUrl: "https://flagcdn.com/w40/gh.png" },
  { code: "MA", name: "Morocco", flagUrl: "https://flagcdn.com/w40/ma.png" },
  { code: "BR", name: "Brazil", flagUrl: "https://flagcdn.com/w40/br.png" },
  { code: "MX", name: "Mexico", flagUrl: "https://flagcdn.com/w40/mx.png" },
  { code: "AR", name: "Argentina", flagUrl: "https://flagcdn.com/w40/ar.png" },
  { code: "CL", name: "Chile", flagUrl: "https://flagcdn.com/w40/cl.png" },
  { code: "CO", name: "Colombia", flagUrl: "https://flagcdn.com/w40/co.png" },
  { code: "PE", name: "Peru", flagUrl: "https://flagcdn.com/w40/pe.png" },
  { code: "VE", name: "Venezuela", flagUrl: "https://flagcdn.com/w40/ve.png" },
  { code: "EC", name: "Ecuador", flagUrl: "https://flagcdn.com/w40/ec.png" },
  { code: "UY", name: "Uruguay", flagUrl: "https://flagcdn.com/w40/uy.png" },
  { code: "CR", name: "Costa Rica", flagUrl: "https://flagcdn.com/w40/cr.png" },
  { code: "PA", name: "Panama", flagUrl: "https://flagcdn.com/w40/pa.png" },
  { code: "GT", name: "Guatemala", flagUrl: "https://flagcdn.com/w40/gt.png" },
  { code: "NZ", name: "New Zealand", flagUrl: "https://flagcdn.com/w40/nz.png" },
];
